# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

per_cell_qc <- function(matrix, featcon, top, limit) {
    .Call(`_scater_per_cell_qc`, matrix, featcon, top, limit)
}

per_feature_qc <- function(matrix, cellcon, limit) {
    .Call(`_scater_per_feature_qc`, matrix, cellcon, limit)
}

top_cumprop <- function(matrix, top) {
    .Call(`_scater_top_cumprop`, matrix, top)
}

sum_row_counts <- function(counts, genes, runs) {
    .Call(`_scater_sum_row_counts`, counts, genes, runs)
}

