#' Sum counts across a set of cells
#' 
#' Create a count matrix where counts for all cells in a set are summed together.
#'
#' @param x For \code{sumCountsAcrossCells}, a numeric matrix of counts containing features in rows and cells in columns.
#' Alternatively, a \linkS4class{SummarizedExperiment} object containing such a count matrix.
#'
#' For \code{aggregateAcrossCells}, a \linkS4class{SingleCellExperiment} or SummarizedExperiment containing a count matrix.
#' @param ids A factor specifying the set to which each cell in \code{x} belongs.
#'
#' Alternatively, a \linkS4class{DataFrame} of such vectors or factors, in which case each unique combination of levels defines a set. 
#' @param exprs_values A string or integer scalar specifying the assay of \code{x} containing the matrix of counts
#' (or any other expression quantity that can be meaningfully summed).
#' @param BPPARAM A \linkS4class{BiocParallelParam} object specifying whether summation should be parallelized.
#' @param ... For the generics, further arguments to be passed to specific methods.
#' 
#' For the \code{sumCountsAcrossCells} SummarizedExperiment method, further arguments to be passed to the ANY method.
#'
#' For \code{aggregateAcrossCells}, further arguments to be passed to \code{sumCountsAcrossCells}.
#' @param use_exprs_values A character or integer vector specifying the assay(s) of \code{x} containing count matrices.
#' @param use_altexps Logical scalar indicating whether aggregation should be performed for alternative experiments in \code{x}.
#'
#' Alternatively, a character vector specifying the names of the alternative experiments to be aggregated.
#'
#' @return 
#' For \code{sumCountsAcrossCells} with a factor \code{ids}, a count matrix is returned with one column per level of \code{ids}.
#' For each feature, counts for all cells in the same set are summed together.
#' Columns are ordered by \code{levels(ids)}.
#'
#' For \code{sumCountsAcrossCells} with a DataFrame \code{ids}, a SummarizedExperiment is returned containing a similar count matrix in the first assay.
#' Each column corresponds to a unique combination of levels in \code{ids} and contains the sum of counts for all cells with that combination.
#' The identities of the levels for each column are reported in the \code{\link{colData}}.
#'
#' For \code{aggregateAcrossCells}, a SummarizedExperiment of the same class as \code{x} is returned,
#' containing summed matrices generated by \code{sumCountsAcrossCell} on all assays specified by \code{use_exprs_values}.
#' Column metadata is retained for the first instance of a cell from each set in \code{ids}.
#' If \code{ids} is a DataFrame, the combination of levels corresponding to each column is also reported in the column metadata.
#'
#' @details
#' This function provides a convenient method for aggregating counts across multiple columns for each feature.
#' A typical application would be to sum counts across all cells in each cluster to obtain \dQuote{pseudo-bulk} samples for further analysis.
#'
#' The behaviour of this function is equivalent to that of \code{\link{colsum}}.
#' However, this function can operate on any matrix representation in \code{object};
#' can do so in a parallelized manner for large matrices without resorting to block processing;
#' and can natively support combinations of multiple factors in \code{ids}.
#'
#' Any \code{NA} values in \code{ids} are implicitly ignored and will not be considered or reported.
#' This may be useful, e.g., to remove undesirable cells by setting their entries in \code{ids} to \code{NA}.
#'
#' @author Aaron Lun
#' @name sumCountsAcrossCells
#'
#' @examples
#' example_sce <- mockSCE()
#' ids <- sample(LETTERS[1:5], ncol(example_sce), replace=TRUE)
#'
#' out <- sumCountsAcrossCells(example_sce, ids)
#' dimnames(out)
#'
#' batches <- sample(1:3, ncol(example_sce), replace=TRUE)
#' out2 <- sumCountsAcrossCells(example_sce, DataFrame(label=ids, batch=batches))
#' out2
NULL

#' @importFrom BiocParallel SerialParam bpmapply
#' @importClassesFrom S4Vectors DataFrame
#' @importFrom methods is
#' @importFrom SummarizedExperiment SummarizedExperiment
.sum_counts_across_cells <- function(x, ids, BPPARAM=SerialParam()) {
    multi <- is(ids, "DataFrame")
    if (multi) {
        coldata <- ids
        ids <- .df_to_factor(ids)
    } 
    if (ncol(x)!=length(ids)) {
        stop("length of 'ids' and 'ncol(x)' are not equal")
    }

    by_set <- split(seq_along(ids) - 1L, ids)
    assignments <- .assign_jobs_to_workers(nrow(x), BPPARAM)
    out_list <- bpmapply(start=assignments$start, end=assignments$end, FUN=.sum_across_cols_internal, 
        MoreArgs=list(by_set=by_set, mat=x), BPPARAM=BPPARAM, SIMPLIFY=FALSE, USE.NAMES=FALSE)

    out <- do.call(rbind, out_list)
    dimnames(out) <- list(rownames(x), names(by_set))

    if (multi) {
        m <- match(as.integer(colnames(out)), ids)
        out <- SummarizedExperiment(list(sum=out), colData=coldata[m,,drop=FALSE])
        colnames(out) <- NULL
    }

    out
}

#' @importFrom S4Vectors selfmatch
.df_to_factor <- function(ids) {
    x <- selfmatch(ids) 
    x[Reduce("|", lapply(ids, is.na))] <- NA_integer_
    x
}

.sum_across_cols_internal <- function(mat, by_set, start, end) 
# Internal function to drag along the namespace.
{
    .Call(cxx_sum_col_counts, mat, by_set, start, end)
}

#' @export
#' @rdname sumCountsAcrossCells
setMethod("sumCountsAcrossCells", "ANY", .sum_counts_across_cells)

#' @export
#' @rdname sumCountsAcrossCells
#' @importFrom SummarizedExperiment assay
setMethod("sumCountsAcrossCells", "SummarizedExperiment", function(x, ..., exprs_values="counts") {
    .sum_counts_across_cells(assay(x, exprs_values), ...)    
})

##########################
##########################

#' @export
#' @rdname sumCountsAcrossCells
setMethod("aggregateAcrossCells", "SummarizedExperiment", function(x, ids, ..., use_exprs_values="counts") {
    FUN <- .create_cell_aggregator(ids, use_exprs_values)
    FUN(x, ...)
})

#' @importClassesFrom S4Vectors DataFrame
#' @importFrom methods is
#' @importFrom SummarizedExperiment assays<- assayNames colData<- colData
.create_cell_aggregator <- function(ids, use_exprs_values) {
    multi <- is(ids, "DataFrame")
    if (multi) {
        coldata <- ids
        ids <- .df_to_factor(ids)
    } 

    force(use_exprs_values)

    function(y, ...) {
        collected <- list()
        for (i in seq_along(use_exprs_values)) {
            collected[[i]] <- sumCountsAcrossCells(y, ids=ids, ..., exprs_values=use_exprs_values[i])
        }
        names(collected) <- .choose_assay_names(x, use_exprs_values)

        m <- match(colnames(collected[[1]]), as.character(ids))
        y <- y[,m]
        assays(y) <- collected
        colnames(y) <- colnames(collected[[1]])

        if (multi) {
            colData(y) <- cbind(colData(y), coldata[m,,drop=FALSE])
            colnames(y) <- NULL
        }

        y
    }
}

#' @export
#' @rdname sumCountsAcrossCells
setMethod("aggregateAcrossCells", "SingleCellExperiment", function(x, ids, ..., use_exprs_values="counts", use_altexps=TRUE) {
    FUN <- .create_cell_aggregator(ids, use_exprs_values)
    y <- FUN(x, ...)
    use_altexps <- .get_altexps_to_use(x, use_altexps)
    for (i in use_altexps) {
        altExp(y, i) <- FUN(altExp(x, i), ...)
    }
    altExps(y) <- altExps(y, withColData=FALSE)[use_altexps]
    y
})
